// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH9apTqN1GyzrTvPExDYobEBpnzSXu7yw',
    appId: '1:911061620336:web:de4789441c933092a3c6b5',
    messagingSenderId: '911061620336',
    projectId: 'flutterfireauth-1b4d5',
    authDomain: 'flutterfireauth-1b4d5.firebaseapp.com',
    storageBucket: 'flutterfireauth-1b4d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyc8D1f7HednCEAgmPjwKWzw5Vdr9ZypU',
    appId: '1:911061620336:android:2a7d5697959d34c8a3c6b5',
    messagingSenderId: '911061620336',
    projectId: 'flutterfireauth-1b4d5',
    storageBucket: 'flutterfireauth-1b4d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Qsdjfz07HARA7EL6ENmyVN5aQII4Bq4',
    appId: '1:911061620336:ios:51802796e18c5572a3c6b5',
    messagingSenderId: '911061620336',
    projectId: 'flutterfireauth-1b4d5',
    storageBucket: 'flutterfireauth-1b4d5.appspot.com',
    iosClientId: '911061620336-hfec1j9g3qrfdh2frdof3maq8jv50ee5.apps.googleusercontent.com',
    iosBundleId: 'com.amolina.flutterFireAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Qsdjfz07HARA7EL6ENmyVN5aQII4Bq4',
    appId: '1:911061620336:ios:51802796e18c5572a3c6b5',
    messagingSenderId: '911061620336',
    projectId: 'flutterfireauth-1b4d5',
    storageBucket: 'flutterfireauth-1b4d5.appspot.com',
    iosClientId: '911061620336-hfec1j9g3qrfdh2frdof3maq8jv50ee5.apps.googleusercontent.com',
    iosBundleId: 'com.amolina.flutterFireAuth',
  );
}
